# Generated by Django 5.0.4 on 2026-05-11 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🍦', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Savanna Scoops', max_length=200)),
                ('tagline', models.CharField(default='Hand-Churned Since 2012', max_length=300)),
                ('address', models.CharField(default='Westlands, Nairobi', max_length=500)),
                ('phone', models.CharField(default='+254 700 000 000', max_length=20)),
                ('email', models.EmailField(default='hello@savanascoops.com', max_length=254)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=150, max_digits=8)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=2000, max_digits=8)),
                ('hero_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1549395156-e0c1fe6fc7a5?auto=format&fit=crop&q=80&w=2000')),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flavors/')),
                ('stock', models.PositiveIntegerField(default=100)),
                ('min_stock', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('high', 'High Stock'), ('low', 'Low Stock'), ('out', 'Out of Stock')], default='high', max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('color_hex', models.CharField(default='#F3E5AB', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_dairy_free', models.BooleanField(default=False)),
                ('allergens', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flavors', to='store.category')),
            ],
            options={
                'ordering': ['-is_featured', '-total_sales'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.flavor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('flavor', 'user')},
            },
        ),
    ]
