services:
  - type: web
    name: savanna-scoops
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python manage.py migrate && python manage.py bootstrap_render_data && gunicorn savanna_scoops.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: ALLOWED_HOSTS
        value: savanna-scoops.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://savanna-scoops.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSLMODE
        value: require
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_SHORTCODE
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_CALLBACK_URL
        sync: false
      - key: MPESA_ENVIRONMENT
        value: sandbox
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
