# Generated by Django 5.0.4 on 2026-08-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_version', models.CharField(default='1.0', max_length=20)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('privacy_accepted', models.BooleanField(default=False)),
                ('privacy_version', models.CharField(default='1.0', max_length=20)),
                ('privacy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Consent',
                'verbose_name_plural': 'User Consents',
            },
        ),
    ]
